//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Cliente.gesReserva {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GestionReservaSOAP", Namespace="http://www.example.org/GestionReserva/")]
    public partial class GestionReserva : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CrearReservaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditarReservaOperationCompleted;
        
        private System.Threading.SendOrPostCallback LeerReservaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarReservaOperationCompleted;
        
        private System.Threading.SendOrPostCallback LeerReservaMailOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GestionReserva() {
            this.Url = global::Cliente.Properties.Settings.Default.Cliente_gesReserva_GestionReserva;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CrearReservaCompletedEventHandler CrearReservaCompleted;
        
        /// <remarks/>
        public event EditarReservaCompletedEventHandler EditarReservaCompleted;
        
        /// <remarks/>
        public event LeerReservaCompletedEventHandler LeerReservaCompleted;
        
        /// <remarks/>
        public event EliminarReservaCompletedEventHandler EliminarReservaCompleted;
        
        /// <remarks/>
        public event LeerReservaMailCompletedEventHandler LeerReservaMailCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/GestionReserva/CrearReserva", RequestNamespace="http://www.example.org/GestionReserva/", ResponseNamespace="http://www.example.org/GestionReserva/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("resultado", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool CrearReserva([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")] System.DateTime fechaEntrada, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")] System.DateTime fechaSalida, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string nombreCliente, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string emailCliente, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] double precio, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool ski, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool material, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool profesor, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool alojamiento, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string salida) {
            object[] results = this.Invoke("CrearReserva", new object[] {
                        fechaEntrada,
                        fechaSalida,
                        nombreCliente,
                        emailCliente,
                        precio,
                        ski,
                        material,
                        profesor,
                        alojamiento});
            salida = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CrearReservaAsync(System.DateTime fechaEntrada, System.DateTime fechaSalida, string nombreCliente, string emailCliente, double precio, bool ski, bool material, bool profesor, bool alojamiento) {
            this.CrearReservaAsync(fechaEntrada, fechaSalida, nombreCliente, emailCliente, precio, ski, material, profesor, alojamiento, null);
        }
        
        /// <remarks/>
        public void CrearReservaAsync(System.DateTime fechaEntrada, System.DateTime fechaSalida, string nombreCliente, string emailCliente, double precio, bool ski, bool material, bool profesor, bool alojamiento, object userState) {
            if ((this.CrearReservaOperationCompleted == null)) {
                this.CrearReservaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearReservaOperationCompleted);
            }
            this.InvokeAsync("CrearReserva", new object[] {
                        fechaEntrada,
                        fechaSalida,
                        nombreCliente,
                        emailCliente,
                        precio,
                        ski,
                        material,
                        profesor,
                        alojamiento}, this.CrearReservaOperationCompleted, userState);
        }
        
        private void OnCrearReservaOperationCompleted(object arg) {
            if ((this.CrearReservaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearReservaCompleted(this, new CrearReservaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/GestionReserva/EditarReserva", RequestNamespace="http://www.example.org/GestionReserva/", ResponseNamespace="http://www.example.org/GestionReserva/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("resultado", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool EditarReserva([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")] System.DateTime fechaEntrada, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")] System.DateTime fechaSalida, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string nombreCliente, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string emailCliente, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] double precio, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool ski, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool material, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool profesor, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool alojamiento, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string salida) {
            object[] results = this.Invoke("EditarReserva", new object[] {
                        id,
                        fechaEntrada,
                        fechaSalida,
                        nombreCliente,
                        emailCliente,
                        precio,
                        ski,
                        material,
                        profesor,
                        alojamiento});
            salida = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EditarReservaAsync(int id, System.DateTime fechaEntrada, System.DateTime fechaSalida, string nombreCliente, string emailCliente, double precio, bool ski, bool material, bool profesor, bool alojamiento) {
            this.EditarReservaAsync(id, fechaEntrada, fechaSalida, nombreCliente, emailCliente, precio, ski, material, profesor, alojamiento, null);
        }
        
        /// <remarks/>
        public void EditarReservaAsync(int id, System.DateTime fechaEntrada, System.DateTime fechaSalida, string nombreCliente, string emailCliente, double precio, bool ski, bool material, bool profesor, bool alojamiento, object userState) {
            if ((this.EditarReservaOperationCompleted == null)) {
                this.EditarReservaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditarReservaOperationCompleted);
            }
            this.InvokeAsync("EditarReserva", new object[] {
                        id,
                        fechaEntrada,
                        fechaSalida,
                        nombreCliente,
                        emailCliente,
                        precio,
                        ski,
                        material,
                        profesor,
                        alojamiento}, this.EditarReservaOperationCompleted, userState);
        }
        
        private void OnEditarReservaOperationCompleted(object arg) {
            if ((this.EditarReservaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditarReservaCompleted(this, new EditarReservaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/GestionReserva/LeerReserva", RequestNamespace="http://www.example.org/GestionReserva/", ResponseNamespace="http://www.example.org/GestionReserva/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("fechaEntrada", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime LeerReserva([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")] out System.DateTime fechaSalida, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string nombreCliente, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string emailCliente, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out double precio, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out bool ski, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out bool material, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out bool profesor, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out bool alojamiento) {
            object[] results = this.Invoke("LeerReserva", new object[] {
                        id});
            fechaSalida = ((System.DateTime)(results[1]));
            nombreCliente = ((string)(results[2]));
            emailCliente = ((string)(results[3]));
            precio = ((double)(results[4]));
            ski = ((bool)(results[5]));
            material = ((bool)(results[6]));
            profesor = ((bool)(results[7]));
            alojamiento = ((bool)(results[8]));
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void LeerReservaAsync(int id) {
            this.LeerReservaAsync(id, null);
        }
        
        /// <remarks/>
        public void LeerReservaAsync(int id, object userState) {
            if ((this.LeerReservaOperationCompleted == null)) {
                this.LeerReservaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLeerReservaOperationCompleted);
            }
            this.InvokeAsync("LeerReserva", new object[] {
                        id}, this.LeerReservaOperationCompleted, userState);
        }
        
        private void OnLeerReservaOperationCompleted(object arg) {
            if ((this.LeerReservaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LeerReservaCompleted(this, new LeerReservaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/GestionReserva/EliminarReserva", RequestNamespace="http://www.example.org/GestionReserva/", ResponseNamespace="http://www.example.org/GestionReserva/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("resultado", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool EliminarReserva([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string salida) {
            object[] results = this.Invoke("EliminarReserva", new object[] {
                        id});
            salida = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarReservaAsync(int id) {
            this.EliminarReservaAsync(id, null);
        }
        
        /// <remarks/>
        public void EliminarReservaAsync(int id, object userState) {
            if ((this.EliminarReservaOperationCompleted == null)) {
                this.EliminarReservaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarReservaOperationCompleted);
            }
            this.InvokeAsync("EliminarReserva", new object[] {
                        id}, this.EliminarReservaOperationCompleted, userState);
        }
        
        private void OnEliminarReservaOperationCompleted(object arg) {
            if ((this.EliminarReservaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarReservaCompleted(this, new EliminarReservaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/GestionReserva/LeerReservaMail", RequestNamespace="http://www.example.org/GestionReserva/", ResponseNamespace="http://www.example.org/GestionReserva/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReservaEdicion[] LeerReservaMail([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string email) {
            object[] results = this.Invoke("LeerReservaMail", new object[] {
                        email});
            return ((ReservaEdicion[])(results[0]));
        }
        
        /// <remarks/>
        public void LeerReservaMailAsync(string email) {
            this.LeerReservaMailAsync(email, null);
        }
        
        /// <remarks/>
        public void LeerReservaMailAsync(string email, object userState) {
            if ((this.LeerReservaMailOperationCompleted == null)) {
                this.LeerReservaMailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLeerReservaMailOperationCompleted);
            }
            this.InvokeAsync("LeerReservaMail", new object[] {
                        email}, this.LeerReservaMailOperationCompleted, userState);
        }
        
        private void OnLeerReservaMailOperationCompleted(object arg) {
            if ((this.LeerReservaMailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LeerReservaMailCompleted(this, new LeerReservaMailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/GestionReserva/")]
    public partial class ReservaEdicion {
        
        private int idField;
        
        private System.DateTime fechaEntradaField;
        
        private System.DateTime fechaSalidaField;
        
        private string nombreClienteField;
        
        private string emailClienteField;
        
        private double precioField;
        
        private bool skiField;
        
        private bool materialField;
        
        private bool profesorField;
        
        private bool alojamientoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaEntrada {
            get {
                return this.fechaEntradaField;
            }
            set {
                this.fechaEntradaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaSalida {
            get {
                return this.fechaSalidaField;
            }
            set {
                this.fechaSalidaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreCliente {
            get {
                return this.nombreClienteField;
            }
            set {
                this.nombreClienteField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string emailCliente {
            get {
                return this.emailClienteField;
            }
            set {
                this.emailClienteField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ski {
            get {
                return this.skiField;
            }
            set {
                this.skiField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool profesor {
            get {
                return this.profesorField;
            }
            set {
                this.profesorField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool alojamiento {
            get {
                return this.alojamientoField;
            }
            set {
                this.alojamientoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CrearReservaCompletedEventHandler(object sender, CrearReservaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearReservaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearReservaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string salida {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void EditarReservaCompletedEventHandler(object sender, EditarReservaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditarReservaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditarReservaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string salida {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void LeerReservaCompletedEventHandler(object sender, LeerReservaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LeerReservaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LeerReservaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaSalida {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string nombreCliente {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string emailCliente {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public double precio {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public bool ski {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[5]));
            }
        }
        
        /// <remarks/>
        public bool material {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[6]));
            }
        }
        
        /// <remarks/>
        public bool profesor {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[7]));
            }
        }
        
        /// <remarks/>
        public bool alojamiento {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[8]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void EliminarReservaCompletedEventHandler(object sender, EliminarReservaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarReservaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarReservaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string salida {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void LeerReservaMailCompletedEventHandler(object sender, LeerReservaMailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LeerReservaMailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LeerReservaMailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReservaEdicion[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReservaEdicion[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591